default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DATABASE_POOL_SIZE") { 5 } %>
  database: <%= ENV['Job-board'] %>
  username: <%= ENV['admin'] %>
  password: <%= ENV['password'] %>

development:
  <<: *default
  database: jerb-board_development
  template: template0

test:
  <<: *default
  database: jerb-board_test
  template: template0

production:
  <<: *default
  template: template0
